config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, only: %i[index new create show destroy] do
    member  do
      resources :bookmarks, only: %i[new create]
    end
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: [:list_id] }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true
  validates :title, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list_id = params[:id]
    if @bookmark.save
      redirect_to list_path(@bookmark.list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @movies = @list.movies
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form_bookmark.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie, collection: Movie.order(:title), prompt: "Choose a Movie" %>
  <%= f.submit "Add Bookmark", class: "btn btn-primary" %>
<% end %>

app/views/bookmarks/new.html.erb
<div class="banner">
  <div class="container banner-text">
    <h1>Add a new <strong>Bookmark</strong></h1>
  </div>
</div>

<%= render 'form_bookmark' %>

<br>

<%= link_to "⬅️ Back", :back %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

    <%# NAVBAR %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="container-fluid">
      <%= image_tag "logo.png", style: "width: 25px" %>
      <%= link_to "➕ Add list", new_list_path, class: "navbar-brand" %>
      <%= link_to "See all lists", "/lists", class: "navbar-brand" %>
    </div>
  </div>

    <div class="container mt-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_form_list.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Add list", class: "btn btn-primary" %>
<% end %>

app/views/lists/index.html.erb
<div class="banner">
  <div class="container banner-text">
    <h1>My <strong>Movie</strong> Watchlist <strong>App</strong>!</h1>
    <p>List your favourite movies...</p>
  </div>
</div>

<%# <%= image_tag("movie_theater.jpg", %>
      <%# <% width: 400, height: 300, crop: :fill) %>

<h1 class="text-center mb-5">Lists</h1>

<div>
  <div class="cards">
    <% @lists.each do |list| %>
      <div class="card-category card-img">
          <%#= cl_image_path list.photo.key, crop: :fill %>
          <%= link_to list.name, list_path(list.id) %>
      </div>
    <% end %>
  </div>
</div>

<div>
</div>

<hr>
<%# style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('= cl_image_path list.photo.name, height: 300, crop: :fill')" %>

app/views/lists/new.html.erb
<div class="banner">
  <div class="container banner-text">
    <h1>Add a new <strong>List</strong></h1>
  </div>
</div>

<div class="container">
  <div class="row">
    <div col-12 col-lg-6>
      <%= render 'form_list' %>
    </div>
  </div>
</div>

<br>

<%= link_to "⬅️ Back", :back %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<h3>Movies</h3>

<div class="movie-container p-3">
  <ul class="d-flex p-3 mb-4">
    <% @movies.each do |movie| %>
      <div>
        <li><h4><%= movie.title %></h4>
        <%= image_tag movie.poster_url, style:"height: 250px; width: auto;", class: "float-rigth rounded float-right" %>
        <p class="w-75"><%= movie.overview %></p>
        <p class="w-75"><strong>Rating:</strong> <%= movie.rating %></p>
        <h4><em>"<%= movie.bookmarks.find_by(list: @list).comment %>"</em></h4></li>
        <div class="mt-4">
          <%= link_to '🗑️ Delete bookmark', bookmark_path(movie.bookmarks.find_by(list: @list)), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class:"d-flex flex-direction-row" %>
        </div>
      </div>
    <% end %>
  </ul>

  <%= link_to '➕ Add bookmark', new_bookmark_path(@list) %>

</div>
<hr>

<%= link_to '🗑️ Delete list', list_path, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
<br>
<br>
<%= link_to "⬅️ Back to all lists", lists_path %>